name: "C++ Plugin CI (Reusable)"

on:
  workflow_call:
    inputs:
      name:
        description: "Name of the plugin to check"
        type: string
        required: true
      libcamera-enable:
        description: "Whether to enable libcamera support"
        type: boolean
        required: false
        default: false
      libcamera-version:
        type: string
        description: "The version of libcamera to use"
        required: false
      clang-version:
        description: "The version of Clang/LLVM to use"
        type: string
        required: false
        default: "18"
      apt-packages:
        description: "Additional apt packages to install (space-separated)"
        type: string
        required: false
        default: ""

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: plugins_source
          fetch-depth: 1
          submodules: 'true'
          persist-credentials: false
      - name: 'ivi-homescreen setup'
        uses: ./plugins_source/.github/actions/homescreen-build
        with:
          name: ${{ inputs.name }}
          homescreen-ref: "feature/dynamic-plugins"
          plugins-ref: ${{ github.sha }}
          clang-version: ${{ inputs.clang-version }}
          libcamera-enable: ${{ inputs.libcamera-enable }}
          libcamera-version: ${{ inputs.libcamera-version }}
          apt-packages: ${{ inputs.apt-packages }}

  format:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
        with:
          path: plugins_source
          fetch-depth: 1
          submodules: 'true'
          persist-credentials: false

      # TODO: Cache clang18 installation
      - name: Install clang-format-18
        run: |
          # Disable man-db (massive speed-up!)
          sudo apt-get remove --purge man-db -yq
          # Install LLVM apt repo key
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          # Add LLVM apt repo
          RELEASE_NAME=$(lsb_release -sc 2> /dev/null || echo "noble")
          echo "deb http://apt.llvm.org/${RELEASE_NAME}/ llvm-toolchain-${RELEASE_NAME}-${{ inputs.clang-version }} main" | sudo tee /etc/apt/sources.list.d/llvm.list
          # Update and install dependencies
          sudo apt-get update -yq
          sudo apt-get install -yq clang-format-18

      - name: find
        working-directory: "${{ github.workspace }}/plugins_source/plugins"
        run: |
          find "${{ inputs.name }}" -type d -name third_party -prune -false -o -name '*.cc' -o -name '*.hpp' -o -name '*.h' > clang-format-files
          echo "Formatting files:"
          cat clang-format-files

      - name: clang-format
        working-directory: "${{ github.workspace }}/plugins_source/plugins"
        run: |
          which clang-format-18
          clang-format-18 --version
          clang-format-18 -n --Werror --files=clang-format-files 2> clang-format-results.txt

      - name: results
        working-directory: "${{ github.workspace }}/plugins_source/plugins"
        if: always()
        run: |
          cat clang-format-results.txt

      - name: upload results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: clang-format-results
          path: "${{ github.workspace }}/plugins_source/plugins/clang-format-*"

  tidy:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v6
        with:
          path: plugins_source
          fetch-depth: 1
          submodules: 'true'
          persist-credentials: false
      - name: 'ivi-homescreen setup'
        uses: ./plugins_source/.github/actions/homescreen-build
        with:
          name: ${{ inputs.name }}
          homescreen-ref: "feature/dynamic-plugins"
          plugins-ref: ${{ github.sha }}
          clang-version: ${{ inputs.clang-version }}
          libcamera-enable: ${{ inputs.libcamera-enable }}
          libcamera-version: ${{ inputs.libcamera-version }}
          apt-packages: ${{ inputs.apt-packages }}

      # NOTE: for some reason doesn't tidy correctly if waypp files are not generated
      - name: Build waypp
        working-directory: ${{github.workspace}}/build
        run: |
          ninja waypp

      - name: clang-tidy
        working-directory: ${{github.workspace}}/plugins_source/plugins
        run: |
          export FILE_LIST=$(find "${{ inputs.name }}" -type d -name third_party -prune -false -o -name '*.cc' -o -name '*.hpp' -o -name '*.h')
          echo $FILE_LIST
          run-clang-tidy \
            -warnings-as-errors='*,-bugprone-macro-parentheses' \
            -export-fixes=tidy-results-suggested-fixes.txt \
            -p ${{github.workspace}}/build \
            $FILE_LIST \
            2>/dev/null \
            | tee tidy-results-log.txt

          # If tidy-results-suggested-fixes.txt contains "Error: " at least once, make the step fail
          set -e
          ! grep -q "Level: Error" tidy-results-suggested-fixes.txt

      - name: Show results
        if: always()
        working-directory: ${{github.workspace}}/plugins_source/plugins
        run: |
          cat tidy-results-log.txt
          cat tidy-results-suggested-fixes.txt

      - name: Publish Report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: clang-tidy-results
          path:  ${{github.workspace}}/plugins_source/plugins/tidy-results-*

  build:
    permissions:
      contents: read
      pull-requests: write
    needs: install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          path: plugins_source
          fetch-depth: 1
          submodules: 'true'
          persist-credentials: false
      - name: 'ivi-homescreen setup'
        uses: ./plugins_source/.github/actions/homescreen-build
        with:
          name: ${{ inputs.name }}
          homescreen-ref: "feature/dynamic-plugins"
          plugins-ref: ${{ github.sha }}
          clang-version: ${{ inputs.clang-version }}
          libcamera-enable: ${{ inputs.libcamera-enable }}
          libcamera-version: ${{ inputs.libcamera-version }}
          apt-packages: ${{ inputs.apt-packages }}

      - name: build
        working-directory: ${{github.workspace}}/build
        run: |
          ninja homescreen

      # # Cache build outputs
      # - name: Cache build outputs
      #   uses: actions/cache/save@v3
      #   with:
      #     path: ${{ github.workspace }}/build
      #     key: ${{ runner.os }}-build-${{ github.run_id }}
  
  codeql:
    # Runner size impacts CodeQL analysis time. To learn more, please see:
    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
    #   - https://gh.io/supported-runners-and-hardware-resources
    #   - https://gh.io/using-larger-runners (GitHub.com only)
    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    # skip if repository is private
    if: github.event.repository.visibility == 'public'
    needs: install
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: c-cpp
          build-mode: manual
        # CodeQL supports the following values keywords for 'language': 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
        # Use `c-cpp` to analyze code written in C, C++ or both
        # Use 'java-kotlin' to analyze code written in Java, Kotlin or both
        # Use 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
        # To learn more about changing the languages that are analyzed or customizing the build mode for your analysis,
        # see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning.
        # If you are analyzing a compiled language, you can modify the 'build-mode' for that language to customize how
        # your codebase is analyzed, see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
    steps:
      - uses: actions/checkout@v6
        with:
          path: plugins_source
          fetch-depth: 1
          submodules: 'true'
          persist-credentials: false
      - name: 'ivi-homescreen setup'
        uses: ./plugins_source/.github/actions/homescreen-build
        with:
          name: ${{ inputs.name }}
          homescreen-ref: "feature/dynamic-plugins"
          plugins-ref: ${{ github.sha }}
          clang-version: ${{ inputs.clang-version }}
          libcamera-enable: ${{ inputs.libcamera-enable }}
          libcamera-version: ${{ inputs.libcamera-version }}
          apt-packages: ${{ inputs.apt-packages }}

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          source-root: plugins_source/plugins/${{ inputs.name }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.

          # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          # queries: security-extended,security-and-quality

      # If the analyze step fails for one of the languages you are analyzing with
      # "We were unable to automatically build your code", modify the matrix above
      # to set the build mode to "manual" for that language. Then modify this step
      # to build your code.
      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

      # Full build step for CodeQL analysis
      - name: Build code for CodeQL
        if: matrix.build-mode == 'manual'
        run: |
          ninja -C ${{github.workspace}}/build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:${{matrix.language}}"
          checkout_path: ${{ github.workspace }}/plugins_source/

  # TODO: add a `docs` job

  # TODO: add a `test` job
